### ISSUE TITLE
[Tracker] - Documentation

### ISSUE THREAD

**Issue by cpswsg** [turtleloveshoes/SumoOnboarding#12]
This issue is tracking all the necessary documentation in the [README.md](/turtleloveshoes/SumoOnboarding/README.md) file.

- [x] Add names of components
- [x] Add names of pages
- [x] Add how to add a custom component
- [x] Add how to edit automatic permissions component 
- [ ] Add how to make a basic REST API call
- [x] Add link to license
- [x] Add link to bug tracker on Bugzilla
- [x] Create a table of contents

See also: #5, #9

**Comment by cpswsg** [comment]
PR: #10 , #11

**Comment by turtlelovesshoes** [comment]
LGTm

**Comment by cpswsg** [comment]
Commits: 1354a24, 05ff91d, 2770a54, b03c23c and 541d5b5
